vmware/cloud-director-named-disk-csi-driver

- pkg/vcdclient/auth.go
- pkg/vcdclient/client.go
When refreshing client using refresh token, isSysadmin boolean for the client should be manually set to true to overwrite the changes made by goVcd during SetToken()
@arunmk @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/12)
> Manually set isSysAdmin boolean when refreshing vcdClient

- pkg/vcdclient/auth.go
- pkg/vcdclient/client.go
Recreate swagger client with updated access token after creating a new access token
@arunmk @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/13)
> [VCDA-2948] Recreate swagger api client with updated access token

- cmd/csi/main.go
- manifests/csi-controller.yaml
- manifests/csi-node.yaml
- pkg/config/cloudconfig.go
- pkg/vcdclient/auth.go
- release/version
They were being passed as secrets and also as VCD config. This
change removes passing as configmap and uses only secrets with
retries.
This change also changes version of main branch to main-branch
so that people can point to the latest unreleased tip.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/17)
> VCDA-3114: Passing user/secret as part of secrets was broken.

- pkg/util/defined_entity_util.go
- pkg/vcdclient/disks.go
- pkg/vcdclient/errors.go
* Change CAPVCD NSS from "capvcd" to "capvcdCluster"
* Add PV to RDE only if RDE doesn't contain NO_RDE prefix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/22)
> Incorporate NO_RDE check into CSI

- pkg/vcdclient/auth.go
- pkg/vcdclient/auth_system_test.go
- pkg/vcdclient/client.go
- pkg/vcdclient/common_system_test.go
* Address issue with system administrator login using refresh token
* Try authenticating to system org and fall back to user org if it fails
Testing done:
* ran system tests
* Executed CPI as system admin and org admin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/34)
> [VCDA-3444] Set authentication as system org user before falling back to userOrg

- pkg/csi/controller.go
- pkg/vcdcsiclient/disks.go
* if disk is already existed/attched/delete/detached, no event would be added into RDE
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/69)
> [VCDA-4022][Beta-blocker][Testfest] Duplicate CSI DiskAttachEvents are happening for a successful disk attachment

- Makefile
- manifests/csi-controller.yaml
- manifests/csi-node.yaml
- release/version
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/73)
> VCDA-4014: make CSI point to 1.3.0-beta. Also remove `.latest` suffix

- go.mod
- go.sum
- vendor/modules.txt
* Updated with command `go get -u github.com/vmware/cloud-provider-for-cloud-director@1.2.z`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/96)
> [VCDA-4602] Consume latest CPI common core from release branch 1.2.z

- manifests/csi-controller-crs.yaml
- manifests/csi-controller.yaml
- manifests/csi-node-crs.yaml
- manifests/csi-node.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/97)
> VCDA-4225: Build internal images for 1.3.z and point to image

- pkg/csi/node.go
In function NodeStageVolume, before mount the device on a directory on the host, need check - if directory exist. And if it doesn't exist then create it.
Fixes this bug:
https://github.com/vmware/cloud-director-named-disk-csi-driver/issues/132
Signed-off-by: dtarasov7 [dtarasov7@gmail.com](mailto:dtarasov7@gmail.com)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/134)
> Stage: Create directory for mount if it doesn't exist 

- manifests/csi-controller-crs.yaml
- manifests/csi-controller-crs.yaml.template
- manifests/csi-controller.yaml
- manifests/csi-controller.yaml.template
- manifests/csi-node-crs.yaml
- manifests/csi-node-crs.yaml.template
- manifests/csi-node.yaml
- manifests/csi-node.yaml.template
-  The registory "k8s.gcr.io" will be deprecated. Use registry.k8s.io instead.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/151)
> [VKC-78] The registory "k8s.gcr.io" will be deprecated. Use registry.k8s.io instead.

- manifests/csi-controller-crs.yaml
- manifests/csi-controller-crs.yaml.template
- manifests/csi-controller.yaml
- manifests/csi-controller.yaml.template
- manifests/csi-node-crs.yaml
- manifests/csi-node-crs.yaml.template
- manifests/csi-node.yaml
- manifests/csi-node.yaml.template
(cherry picked from commit a233d5a457e982c4bbcd3efc49c63359cf7eb6e1)
- Use registry.k8s.io to replace k8s.gcr.io
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/154)
> [VKC-78] Use registry.k8s.io to replace k8s.gcr.io (#151)

- manifests/csi-controller.yaml
- manifests/csi-node.yaml
- Use registry.k8s.io to replace k8s.gcr.io
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/155)
> [VKC-79] Use registry.k8s.io to replace k8s.gcr.io

- README.md
- Add the upgrade instruction on CSI Controller: from StatefulSet to Deployment.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/168)
> [VKC-62] [Github Doc]CSI manifest change (stateful set to deployment) - how do upgrades work?

- pkg/csi/controller.go
To track which named disk belongs to which cluster, it is necessary to inject ClusterID to NamedDisks. 
Having ClusterID on NamedDisks is necessary for the clean-up process. 
An alternative solution to https://github.com/vmware/cloud-director-named-disk-csi-driver/issues/124
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/174)
> Set description of named disks as ClusterID

- manifests/csi-controller-crs.yaml
- manifests/csi-controller-crs.yaml.template
- manifests/csi-controller.yaml
- manifests/csi-controller.yaml.template
- manifests/csi-node-crs.yaml
- manifests/csi-node-crs.yaml.template
- manifests/csi-node.yaml
- manifests/csi-node.yaml.template
1. Remove the `pv` suffix that causes issues in mounting
2. set up nodeAffinity with control-plane
Ran tests in tests/e2e 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/184)
> VKC-113: K8s 1.25 support:

- tests/e2e/storageProfile_test.go
- tests/e2e/xfs_fsType_test.go
- Fix CSI tests – use userOrg instead of "system"
- Skip StorageProfile tests if not sysadmin
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/206)
> [VKC-129] Update CSI system tests – use correct userOrg for xfs tests, skip StorageProfile tests if not sysadmin

- tests/e2e/storageProfile_test.go
- tests/e2e/xfs_fsType_test.go
…, skip StorageProfile tests if not sysadmin (#206)
(cherry picked from commit 073ffc8d8937bebbc60f884bc689ee6a5229e03e)
- Cherrypick commit 073ffc8d8937bebbc60f884bc689ee6a5229e03e
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/208)
> [VKC-129] Cherry-pick: Update CSI system tests – use correct userOrg for xfs tests, skip StorageProfile test if not sysadmin

- tests/e2e/dynamic_provisioning_test.go
- tests/e2e/static_provisioning_test.go
- tests/e2e/xfs_fsType_test.go
- tests/utils/disk_util.go
- tests/utils/kubernetes_ops_util.go
- Refactor CSI tests to be more resilient
- Update PV orderings, as there could be race conditions due to randomized tests where a PV can be deleted by PVC, but delete with code also.
- Update containerImage to use staging to prevent API rate limitings in public docker
- Increase CSI specific timeouts
- Update `GetPVByNameViaRDE()` to return the expected error if field is missing
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> [VKC-135] Refactor CSI tests to be more resilient

- tests/e2e/e2e_suite_test.go
During merge of cse-2-24-next branch into main, the private registry info in e2e test was overwritten to an old private registry. This PR reverts the change related to private registry in e2e tests.
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/239)
> Fix CSI test for air-gapped env

- artifacts/bom.json.template
- artifacts/dependencies.txt.template
- Updates bom.json.template and dependencies.txt.template to use 'vmware-cloud-director/*' for consistency
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/253)
> [VCDA-6991] Update dependency and bom template to use vmware-cloud-director as image paths

- README.md
- pkg/csi/controller.go
- pkg/csi/node.go
- pkg/vcdcsiclient/disks.go
- samples/pvc-blockmount-debugger.yaml
- samples/pvc-blockmount.yaml
- samples/pvc-ext4-debugger.yaml
- samples/pvc-ext4.yaml
- samples/pvc-xfs.yaml
- samples/sc-blockmount.yaml
- samples/sc-ext4.yaml
- samples/sc-xfs.yaml
- This adds block mount support to the CSI driver
I ran the following manual tests:
1. Install the storageClass
2. Create a block PVC
3. Create a pod that consumes the block storage.
4. Log into the pod
5. Note that the storage is presented as a block volume in the storage
6. Format the storage and mount it to verify that the storage is accessible. Create a dummy file with some content.
7. Delete the pod and recreate it. Mount the storage and verify that the  file is still accessible.
8. Delete the pod.
9. Delete the PVC
Not Applicable. …
> VKC-6: Block mount support

- Makefile
- artifacts/bom.json.template
- artifacts/dependencies.txt.template
- Reverts the behavior of 1.6.z builds back to 1.5.z
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/261)
> [VKC-194] Revert makefile and registry changes to behavior from 1.5.z

- Makefile
- Small fix to include registry as part of docker-archive make target
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/262)
> [VKC-194] Small fix: Update docker-archive with registry reference

- tests/e2e/dynamic_provisioning_test.go
- tests/e2e/e2e_suite_test.go
- tests/utils/kubernetes_ops_util.go
- Fix CSI volume expansion test, parameterize defaultStorageClassProfi
Ran 22 of 25 Specs in 546.607 seconds
SUCCESS! -- 22 Passed | 0 Failed | 0 Pending | 3 Skipped
--- PASS: TestCSIAutomation (569.62s)
PASS
Skipped tests are from xfs_fsType_test.go due to being a tenant user.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/269)
> [VKC-212] Fix CSI volume expansion test, parameterize defaultStorageClassProfile
