- README.md
Documentation with some beta details
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/4)
> VCDA-2873: Basic Documentation with beta details

- manifests/vcloud-basic-auth.yaml
- pkg/csi/controller.go
- pkg/vcdclient/auth.go
- pkg/vcdclient/client.go
- pkg/vcdclient/disks.go
- pkg/vcdclient/vms.go
Exchange the refresh token with access token at all the top level functions used in CSI
Testing done:
* Set token timeout to 5 mins and try creating a volume after token expiry. PV should be created without issues
@arunmk @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/9)
> [VCDA-2527] Changes to use create access token at all top level functions

- cmd/csi/main.go
- manifests/vcloud-csi-config.yaml
- pkg/config/cloudconfig.go
- pkg/vcdclient/auth.go
- pkg/vcdclient/client.go
- pkg/vcdclient/common_system_test.go
- pkg/vcdclient/vms.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/11)
> VCDA-2922: Allow sysadmin user to use CSI

- Dockerfile
Tested with disk creation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/7)
> VCDA-2896: Use photon as base image

- README.md
1. Cleaned up the CSI User which caused confusion
2. Removed the Beta content
3. Added the refresh token rights
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/15)
> VCDA-2426: Docs for 1.0.0 GA

- pkg/util/defined_entity_util.go
- pkg/vcdclient/auth.go
- pkg/vcdclient/disks.go
Signed-off-by: ltimothy7 <66969084+ltimothy7@users.noreply.github.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/18)
> [VCDA-3046] CSI supporting capvcd schema

- pkg/config/cloudconfig.go
- pkg/vcdclient/auth.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/20)
> VCDA-3151: CSI counterpart for fixing username/password regression

- NOTICE.txt
- open_source_license.txt
Update OSL for CSI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/23)
> [VCDA-3218]Update OSL for CSI

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/24)
> VCDA-3120: update README for 1.1.0

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdclient/auth.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdclient/client.go
- vendor/modules.txt
* Update vendor folder to include fix for system admin refresh token in vcdClient
Testing done:
* Executed CPI with system admin token in TKGm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/33)
> [VCDA-3444] Update Vendor folder with fix for system admin refresh token issue in vcdClient

- pkg/util/defined_entity_util.go
* Changes to only compare NSS and Vendor when determining entity type of the RDE
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/35)
> Compare only vendor and nss while determining entity type of RDE

- README.md
* Doc changes for 1.1.1 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/37)
> Update README for 1.1.1 release

- manifests/csi-controller.yaml
- manifests/csi-node.yaml
Fixes VCDA-3413
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/40)
> Manifest changes to make CSI work in k8s 1.22+

- README.md
* Change CSI image repository name from private harbor to public harbor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/39)
> Fixed image in documentation

- pkg/config/cloudconfig.go
* Updated cloudConfig to trim trailing slashes from host after parsing the config
* Finished the validation testing via replacing the updated image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/43)
> fix trailing slash(s) issue #VCDA-3512

- pkg/vcdcsiclient/common_system_test.go
- pkg/vcdcsiclient/disks_system_test.go
- testdata/config_test.yaml
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/config/cloudconfig.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/config/vcloud-ccm-config.yaml
- vendor/modules.txt
Ticket: VCDA-3546
* Fix an issue with library imports during CSI unit testing.
* Pass two unit test **TestDiskCreateAttach** and **TestRdeEtag** on personal cluster.
* Configuration file is kept for further use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42)
> fix the unit test failing issue #VCDA 3546

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/45)
> Add details of changes in 1.2

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/47)
> Fix speling and version

- pkg/vcdcsiclient/disks_system_test.go
Remove if-else checking for Unit Test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/54)
> [Quick-fix] Remove if-else checking for Unit Test

- cmd/csi/main.go
- go.mod
- go.sum
- manifests/csi-controller.yaml
- pkg/csi/driver.go
- pkg/util/defined_entity_util.go
- pkg/vcdcsiclient/disks.go
- pkg/vcdcsiclient/disks_system_test.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/defined_entity.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
* Created ENV `UPGRADE_RDE` and flag parameter `--upgrade-rde string               CSI upgrade rde`
* Get persistentVolumes list from old RDE and wipe off section `persistentVolumes`
* Add Todo comments on several places. We should record errors in `status.csi.errors` in a separate PR
* Passed the Testing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55)
> [VCDA-3441] Implement RDE upgrade logic during CSI start up

- manifests/csi-controller.yaml
- manifests/csi-node.yaml
- release/version
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/57)
> VCDA-3737: Point VKP branch to vkp docker image

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/defined_entity.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
* Update the latest CPI for vkp branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/60)
> [Quick Fix]Update the latest CPI for vkp branch

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/util/set.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/defined_entity.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/defined_entity_util.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/61)
> update CPI dependency

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/client.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/defined_entity.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/65)
> VCDA-3815 update cpi dependency

- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/66)
> change order in which we are installing e2fsprogs and udev

- Dockerfile
- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/client.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/68)
> VCDA-3815 0627 vkp sync

- NOTICE.txt
- open_source_license.txt
Add OSL files for CSI 1.3 beta
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/71)
> [VCDA-3999] Add OSL for CSI 1.3 beta

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/NOTICE.txt
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/vapp.go
- vendor/modules.txt
* Update common core in CSI to latest commit of CPI vkp branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/72)
> [VCDA-4027] [Beta-blocker] Update common core in CSI to latest commit of CPI vkp branch

- manifests/csi-controller.yaml
Fixes #64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/74)
> VCDA-4081: Set fstype to enable fsGroup

- go.mod
- go.sum
- manifests/csi-controller.yaml
- manifests/csi-node.yaml
- release/version
- vendor/modules.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/77)
> VCDA-4093: Make CSI point to harbor:main; also update common-core

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/auth.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/vapp.go
- vendor/modules.txt
* Update latest CPI content in vendor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/80)
> [VCDA-4211] Update latest CPI content in vendor

- README.md
Docs for wire logging
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/83)
> Add docs for wire logging

- pkg/vcdcsiclient/disks.go
* Add retry logic to UpgradeRDEPersistentVolumes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/85)
> [VCDA-4388] Add retry logic to UpgradeRDEPersistentVolumes

- Makefile
- manifests/csi-controller-crs.yaml
- manifests/csi-controller-crs.yaml.template
- manifests/csi-controller.yaml.template
- manifests/csi-node-crs.yaml
- manifests/csi-node-crs.yaml.template
- manifests/csi-node.yaml.template
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/87)
> VCDA-4332: Embed git commit into image tag name

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/vapp.go
- vendor/modules.txt
Signed-off-by: rliang88 <rliang@vmware.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/86)
> [VCDA-4386] updated vendor package with latest CPI commit

- manifests/csi-controller-crs.yaml
- manifests/csi-controller.yaml
- manifests/csi-node-crs.yaml
- manifests/csi-node.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/88)
> Update CSI Image tags for refresh

- manifests/csi-controller-crs.yaml
- manifests/csi-controller.yaml
- manifests/csi-node-crs.yaml
- manifests/csi-node.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/89)
> VCDA-4469: FC build for CSI

- manifests/csi-controller-crs.yaml
- manifests/csi-controller.yaml
- manifests/csi-node-crs.yaml
- manifests/csi-node.yaml
* Update imagetag tag to last code change commit 3712c61
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/90)
> [VCDA-4511] Update imagetag to commit 3712c61

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/81)
> Typofix in README

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/defined_entity.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/vapp.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_org_vdc_networks.go
- vendor/modules.txt
* Consume updated common core up to commit 03833ee
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/91)
> [VCDA-4566] Consume updated CPI common core for DB Audit

- go.mod
- go.sum
- pkg/vcdcsiclient/disks.go
- pkg/vcdcsiclient/disks_system_test.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/defined_entity.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/ipam.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_certificate_library_modified.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_defined_entity.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_edge_gateway.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_edge_gateway_load_balancer_pool.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_edge_gateway_load_balancer_pools.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_edge_gateway_load_balancer_virtual_service.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_edge_gateway_load_balancer_virtual_services_modified.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_edge_gateway_nat_rule.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_edge_gateway_nat_rules.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_load_balancer_service_engine_group_assignments.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_org_vdc_network.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_org_vdc_networks.go
- vendor/modules.txt
* Includes recent log message updates
* Includes tenant org context in defined entity calls
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/93)
> [VCDA-4594] Update common core with modified cloud api calls to include tenant org context

- manifests/csi-controller-crs.yaml
- manifests/csi-controller.yaml
- manifests/csi-node-crs.yaml
- manifests/csi-node.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/94)
> [VCDA-4615] Update image tag to the latest main from 10/7

- release/version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/95)
> VCDA-4254: Branch for 1.3.z

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_certificate_library_modified.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/vcdconstants.go
- vendor/modules.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/98)
> [VCDA-4634] Refresh CPI common core in CSE 1.3.z branch (using hash b8bdde7 from CPI 1.2.z branch)

- manifests/csi-controller-crs.yaml
- manifests/csi-controller.yaml
- manifests/csi-node-crs.yaml
- manifests/csi-node.yaml
Update for consuming common core 8a6fd12
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/99)
> [VCDA-4640]: Update image tags and refresh image for CSI 1.3.z

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_certificate_library_modified.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/vcdconstants.go
- vendor/modules.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/100)
> [VCDA-4661] Refresh common core with main using hash 8574691ef708 in CSI main branch 

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/auth.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/defined_entity.go
- vendor/modules.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/102)
> [VCDA-4745] Update common core from CPI 1.2.z commit ee1c9e6

- manifests/csi-controller-crs.yaml
- manifests/csi-controller.yaml
- manifests/csi-node-crs.yaml
- manifests/csi-node.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/103)
> [VCDA-4753] Refresh CSI 1.3.z image up to commit 9589922

- open_source_license.txt
* Update OSL for CSI 1.3 GA
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/104)
> [VCDA-4230] Update OSL for CSI 1.3 GA

- open_source_license.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/105)
> [VCDA-4230] Update OSL for CSI 1.3 GA (#104)

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
* Refresh common core in CSI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/106)
> [VCDA-4762] Update common core in CSI with commit fc36ada from CPI 1.2.z

- manifests/csi-controller-crs.yaml
- manifests/csi-controller.yaml
- manifests/csi-node-crs.yaml
- manifests/csi-node.yaml
* Update CSI image tags in manifests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/107)
> [VCDA-4761] Update CSI image tags in manifests

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/auth.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/defined_entity.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/108)
> [VCDA-4802] Refresh CSI main common core with CPI main commit 8946fef

- manifests/csi-controller-crs.yaml
- manifests/csi-controller.yaml
- manifests/csi-node-crs.yaml
- manifests/csi-node.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/109)
> [VCDA-4807] Update CSI main image tag to commit 6e69474

- go.mod
- go.sum
- vendor/modules.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/111)
> Undo latest CPI commit on CSI 1.3.0

- README.md
* 1.3.0 release docs
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
* added links to other docs
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
* remove .latest from img
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
* updated review comments
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
* reformatted README
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
* updated CSE 4.0 assumption
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
(cherry picked from commit 4866d66acbe9426c2b6cf7ec15dd8c80ccb34576)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/114)
> [VCDA-4771] 1.3.0 release docs (#112)

- pkg/csi/node.go
* add rescanDiskInVM func() into CSI
* Test SCSI bus rescan is performed successfully inside the VM.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116)
> [VKC-20] fix issue - failed to mount volume to VM

- pkg/csi/node.go
* add rescanDiskInVM func
* add nit change
* add changes
* add os.writeFIle
(cherry picked from commit a279d627c93ffa18f5ee2192fd8a36acdf3f484f)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/118)
> [VKC-20-cherrypick] fix issue - failed to mount volume to VM (#116)

- schema/schema_1_1_0.json
* Created a schema definition for CSI status section in CAPVCD RDE schema
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/113)
> [VCDA-4886]Update CSI repo with CSI status schema

- Makefile
- manifests/csi-controller-crs.yaml.template
- manifests/csi-controller.yaml.template
- manifests/csi-node-crs.yaml.template
- manifests/csi-node.yaml.template
* Updated hard-coded values, tested locally running `make dev` and saw all 4 CRS files get updated as `$version.$commit`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/123)
> [VKC-22] Remove hardcoded main-branch from template files for Makefile

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/k8sclient.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/rde_utils.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/vcd_utils.go
- vendor/modules.txt
*  update CPI testing common code to the latest version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/130)
> [VKC-47] update CPI testing common code to the latest version

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/capiyaml_utils.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/client.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/k8sclient.go
- vendor/modules.txt
* updated CSI vendor with newest cpi common testing core
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/133)
> [VKC-56] updated CSI vendor with newest cpi common testing core

- artifacts/default-csi-controller-crs-airgap.yaml.template
- manifests/csi-controller-crs.yaml
- manifests/csi-controller-crs.yaml.template
- manifests/csi-controller.yaml
- manifests/csi-controller.yaml.template
* Change CSI controller to be a Deployment rather than StatefulSet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/137)
> [VKC-61]Change CSI controller to be a Deployment rather than StatefulSet

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/client.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/k8sclient.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/vapp.go
- vendor/modules.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/142)
> [VKC-60] [common-core] sync with CPI common-core for TKG 1.6.1

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
- sync with CPI common-core for "Add Ovdc check when getting ovdc network"
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/147)
> [VKC-71] [common-core] sync with CPI common-core (a1a149d80f32) for "Add Ovdc check when getting ovdc network"

- .gitlab-ci.yml
- Makefile
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/141)
> [VCDA-4850] Add build file to push image to registry

- pkg/vcdcsiclient/disks.go
- fix typo in CSI status upgrade
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/148)
> [VKC-72][Testfest-2-27] CodeFix for "CSI RDE update wipes off VCD-KE status"

- Dockerfile
- pkg/csi/node.go
- pkg/util/util.go
- samples/my-pvc-ext4.yaml
- samples/my-pvc-xfs.yaml
…ext4 / filesystem: xfs)" (#149)
* add xfs support
* [VKC-68] change my-pvc.yaml file name
* add more detailed comment
---------
(cherry picked from commit a20d5106472a3dd3f9e65288e4f3f1d1df1d262c)
- [cherryPick] Fix XFS issue - the volumes should be formatted and mounted as XFS when XFS is specified in storageClass
Fixes #
- - -
This …
> [VKC-82] Fix XFS issue - the volumes should be formatted and mounted as XFS when XFS is specified in storageClass

- Dockerfile
- pkg/csi/node.go
- pkg/util/util.go
- samples/my-pvc-ext4.yaml
- samples/my-pvc-xfs.yaml
* add xfs support
* [VKC-68] change my-pvc.yaml file name
* add more detailed comment
---------
(cherry picked from commit a20d5106472a3dd3f9e65288e4f3f1d1df1d262c)
- [VKC-68] fix CSI Issue - "Filesystem XFS is mounted as ext4 (fsType:ext4 / filesystem: xfs)" (#149)
Fixes #
- - -
This change is [<img …
> [VKC-81] Fix XFS issue - the volumes should be formatted and mounted as XFS when XFS is specified in storageClass

- README.md
- Document on Github 1.2.1 Patch
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/164)
> [VKC-86] Document on Github 1.2.1 Patch

- go.mod
- go.sum
- vendor/modules.txt
- Update CSI 1.4.z common core to use CPI common core from 1.4.z 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/169)
> [VKC-98] Update CSI 1.4.z common core to use CPI common core from 1.4.z

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/client.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/k8sclient.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/vcd_utils.go
- vendor/modules.txt
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/175)
> [VKC-101][common-core] sync with CPI common-core for the updated testingSdk

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/client.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/k8sclient.go
- vendor/modules.txt
-  [Common Core]Sync the latest CPI common code - remove storageClass functions && add config inside TestingClient
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/177)
> [VKC-101] [Common Core]Sync the latest CPI common code - remove storageClass functions && add config inside TestingClient

- Dockerfile
- Makefile
- go.mod
- go.sum
- upgrade golang version to 1.19
- go mod edit=1.19
- go mod tidy
- go mod vendor
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/183)
> [VKC-117] upgrade golang version to 1.19

- Makefile
- manifests/csi-controller-crs.yaml
- manifests/csi-controller-crs.yaml.template
- manifests/csi-controller.yaml
- manifests/csi-controller.yaml.template
- manifests/csi-node-crs.yaml
- manifests/csi-node-crs.yaml.template
- manifests/csi-node.yaml
- manifests/csi-node.yaml.template
- 
Did a make and then a docker pull
N/A
Fixes #
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/187)
> VKC-122: Move internal registry to projects-stg

- tests/e2e/dynamic_provisioning_test.go
- tests/e2e/e2e_suite_test.go
- tests/e2e/static_provisioning_test.go
- tests/e2e/storageProfile_test.go
- tests/utils/disk_util.go
- tests/utils/kubernetes_ops_util.go
- Fix static provisioning failure
- Add `userOrg` as input
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/188)
> [VKC-121] Fix static provisioning failure

- Dockerfile
- Makefile
- optimize image and layers
- update image to a newer photon release
- update to a static binary
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/186)
> fix: optimize image and move to static binary

- Makefile
- artifacts/bom.json.template
- artifacts/default-csi-controller-crs-airgap.yaml.template
- artifacts/default-csi-node-crs-airgap.yaml.template
- artifacts/dependencies.txt.template
- manifests/csi-controller-crs.yaml.template
- manifests/csi-controller.yaml.template
- manifests/csi-node-crs.yaml.template
- manifests/csi-node.yaml.template
- Updates the tagging of airgapped artifacts to `$version.$gitSha`
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/193)
> [VCDA-5806] Ensure airgapped container tags are same as binary image tags

- README.md
when cross-ported.
Also move the feature matric up based on feedback from Stephen
- 
Looked at README.md
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/196)
> VKC-125: Add changes in `main`. These should be changed to 1.4.0

- open_source_license.txt
- Update CSI 1.4.0 GA OSL file
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/199)
> [VKC-128] Update CSI 1.4.0 GA OSL file

- open_source_license.txt
(cherry picked from commit 8f6b2f292014864de922f953853efccc5ac35cdf)
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/200)
> [VKC-128] Update CSI 1.4.0 GA OSL file(#199)

- open_source_license.txt
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/204)
> [VKC-128] update OSL file

- open_source_license.txt
(cherry picked from commit ce796499271adf2f734dc25c82366a6044da22bc)
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/205)
> [VKC-128] update OSL file (#204)

- README.md
cherryPick from 9e4e8389f2cb0a74f105497d792a8484d72bb723
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/209)
> [VKC-133] Update CSI 1.4.z Github documentation (#207)

- manifests/csi-controller-crs.yaml
- manifests/csi-controller-crs.yaml.template
- manifests/csi-controller.yaml
- manifests/csi-controller.yaml.template
- manifests/csi-node-crs.yaml
- manifests/csi-node-crs.yaml.template
- manifests/csi-node.yaml
- manifests/csi-node.yaml.template
- Update image tags on manifests to public harbor version 1.4.0
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/211)
> [VKC-134] Update image tags to 1.4.0

- manifests/csi-controller-crs.yaml
- manifests/csi-controller-crs.yaml.template
- manifests/csi-controller.yaml
- manifests/csi-controller.yaml.template
- manifests/csi-node-crs.yaml
- manifests/csi-node-crs.yaml.template
- manifests/csi-node.yaml
- manifests/csi-node.yaml.template
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/212)
> [Cherry pick][VKC-134] Update image tags to 1.4.0 (#211)

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/k8sclient.go
- vendor/modules.txt
- Update common core sync with CPI main branch commit e8d9efd
- Main purpose of this sync is to increase test automation timeouts
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/214)
> [VKC-136] Update common core sync with CPI main commit e8d9efd

- tests/e2e/dynamic_provisioning_test.go
- tests/e2e/e2e_suite_test.go
- tests/e2e/static_provisioning_test.go
- tests/e2e/xfs_fsType_test.go
- tests/utils/kubernetes_ops_util.go
- Uses environment variables to indicate whether it's an airgap run or not, and use correct images for Deployment creation 
- Refactor CreateDeployment into kubernetes ops util
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/216)
> [VKC-137] Add airgap and staging image support for CSI tests

- go.mod
- go.sum
- vendor/github.com/sethvargo/go-password/LICENSE
- vendor/github.com/sethvargo/go-password/password/generate.go
- vendor/github.com/sethvargo/go-password/password/mock.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/k8sclient.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/vapp.go
- vendor/modules.txt
- Update Common core
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/220)
> [VKC-141] sync CPI common core

- Makefile
- go.mod
- Upgrade go version to 1.20
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/218)
> [VKC-140] upgrade go version to 1.20

- go.mod
- go.sum
- vendor/github.com/sethvargo/go-password/LICENSE
- vendor/github.com/sethvargo/go-password/password/generate.go
- vendor/github.com/sethvargo/go-password/password/mock.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/k8sclient.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/vapp.go
- vendor/modules.txt
- Updating common core to point to top of CPI 1.4.z branch
Built the binary
Fixes #VKC-146
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/222)
> VKC-146: update common core to point to top of 1.4.z CPI branch

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/client.go
- vendor/modules.txt
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/224)
> [VKC-148] common core sync from cpi main commit e68e5d199d99

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/client.go
- vendor/modules.txt
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/225)
> [VKC-148] common core sync from cpi 1.4.z commit 8134f65

- open_source_license.txt
- Update OSL file
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/227)
> [VKC-144] Update OSL for CSI 1.4.1 GA

- tests/e2e/e2e_suite_test.go
- Update the test automation image to new registry
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/229)
> [VKC-151][Tests] Update the testing image to new registry

- tests/e2e/e2e_suite_test.go
(cherry picked from commit 42c885721086622329f26b40fbe6037fc84f022c)
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/230)
> [VKC-151] Cherrypick: Update the testing image to new registry (#229)

- manifests/csi-controller-crs.yaml
- manifests/csi-controller.yaml
- manifests/csi-node-crs.yaml
- manifests/csi-node.yaml
- update manifests for CSI 1.4.1
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/232)
> update manifests for CSI 1.4.1 release

- go.mod
- go.sum
- vendor/modules.txt
- Update CPI common core to the latest commit
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/236)
> [VKC-159] Update CPI common-core to the latest commit

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient_36_0/model_edge_load_balancer_pool_modified.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient_37_2/model_edge_load_balancer_pool_modified.go
- vendor/modules.txt
- common core update
- Built binary
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/240)
> VKC-163: update common core for 4.2 FC

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
- Update CSI common core with CPI 1.5.z commit 203ccc9
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/243)
> [VKC-178] Update CSI common core with CPI release branch commit 203ccc9

- manifests/csi-controller-crs.yaml
- manifests/csi-controller.yaml
- manifests/csi-node-crs.yaml
- manifests/csi-node.yaml
- make manifests point to 1.5.0
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/247)
> VKC-180: update manifests to point to 1.5.0

- manifests/csi-controller-crs.yaml
- manifests/csi-controller.yaml
- manifests/csi-node-crs.yaml
- manifests/csi-node.yaml
This should have been done as part of cutting the branch
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/248)
> VKC-183: Update manifests in main

- open_source_license.txt
- Update OSL for CSE 1.5.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/249)
> [VKC-184] Update OSL 

- open_source_license.txt
- updated OSL for CSI 1.5.0
Signed-off-by: Sakthi Sundaram <sakthisunda@yahoo.com>
(cherry picked from commit 550d7407719e619c996a567a9cf983c906df73c0)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/250)
> [VKC-184] Update-OSL (cherry pick)

- pkg/csi/node.go
FYI: https://github.com/kubernetes/kubernetes/pull/121978
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/251)
> remove pod mount path when NodeUnpublishVolume is called

- Makefile
- Remove references of `$(REGISTRY)` from Makefile
- Use projects-stg as the hardcoded value for pushing images (including sig store components)
- This is because in the CI yaml file we will pull and tag, so it is ok to hardcode here
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/254)
> [VCDA-6929] Remove references of registry from Makefile

- Makefile
- Add gobuild make targets
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/257)
> [VCDA-6933] Consolidate makefile with appropriate gobuild targets

- Dockerfile
Good practice to keep up with newer base image releases to pick up fixes in OS packages.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/259)
> build: update base image to photon:4.0-20240120

- Makefile
- go.mod
- go.sum
- upgrade go version to v1.21.7
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/265)
> [VKC-203] upgrade go version to v1.21.7

- go.mod
- go.sum
- pkg/csi/controller.go
- pkg/vcdcsiclient/disks_system_test.go
- tests/e2e/dynamic_provisioning_test.go
- tests/e2e/static_provisioning_test.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/client.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/vcd_utils.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/client.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/org.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/vapp.go
- vendor/modules.txt
- Common-core sync to allow OVDC IDs to be passed instead of names
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/270)
> VKC-214: common-core sync to use OVDC ID other than name

- artifacts/default-csi-controller-crs-airgap.yaml.template
- artifacts/default-csi-node-crs-airgap.yaml.template
- 
Created cluster using CSE
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/271)
> VKC-216: Manifests in artifacts directory should also have the zone info

- pkg/csi/controller.go
- pkg/vcdcsiclient/disks.go
- There were some places where the VDC __object__ was sent as nil, and there were a few places where the zone object was checked, but it could have zero zones. That caused the disk to not be created. This change fixed that.
- There is another cleanup where I reorganized a small function. I moved from an object being passed to  VDC name being passed.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> VKC-213: Fix non-AZ clusters

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/capiyaml_utils.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
- Sync the latest CPI common code - 6dd634
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/274)
> [VKC-218] Sync the latest CPI common code in CSI - 6dd634

- tests/e2e/dynamic_provisioning_test.go
- tests/e2e/e2e_suite_test.go
- tests/e2e/static_provisioning_test.go
- tests/e2e/storageProfile_test.go
- tests/e2e/xfs_fsType_test.go
- tests/utils/kubernetes_ops_util.go
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/277)
> [VKC-168] make tests execute in multi az environment
